SELECT code, nom, prenom, categorie, count(code_pers) as nombreEmpruntEffectue FROM `livre_emprunt` le left join (`adherent` a left join `personne` p on a.id_pers = p.id) on le.code_pers = a.id_adh where id_adh is not null and (le.date_emprunt <= '2024-12-31' and le.date_emprunt >= '2024-01-01') group by code_pers order by nombreEmpruntEffectue desc

INSERT INTO `dewey`(`code`,`titre`, `description`) VALUES ('000' ,'Generalite',"Cette catégorie couvre les sujets généraux et l'informatique, y compris les encyclopédies, les journaux, les périodiques, et la gestion de l'information. Elle inclut également des ouvrages sur les bibliothèques et l'information, et sur des sujets variés ne rentrant pas facilement dans d'autres catégories.");
INSERT INTO `dewey`(`code`,`titre`, `description`) VALUES ('100' ,'Philosophie',"Cette classe traite de la philosophie, de la métaphysique, de l'épistémologie, de l'éthique, et des différents systèmes philosophiques. Elle inclut aussi la psychologie, abordant les théories psychologiques, le comportement humain, et le développement personnel.");
INSERT INTO `dewey`(`code`,`titre`, `description`) VALUES ('200' ,'Religion',"Les ouvrages de cette catégorie abordent les religions du monde entier, la théologie, les textes religieux, et les philosophies religieuses. Elle comprend également les écrits sacrés, les doctrines, et les pratiques des différentes religions, comme le christianisme, l'islam, le bouddhisme, et l'hindouisme.");
INSERT INTO `dewey`(`code`,`titre`, `description`) VALUES ('300' ,'Sciences sociales',"Cette catégorie est consacrée aux sciences sociales et humaines, incluant la sociologie, l'économie, le droit, la politique, et l'éducation. Elle traite des questions liées aux interactions humaines, aux sociétés, et aux institutions sociales comme la famille et l'éducation.");
INSERT INTO `dewey`(`code`,`titre`, `description`) VALUES ('400' ,'Langues',"Cette classe inclut les ouvrages sur les langues, leur apprentissage, la linguistique et la grammaire. Elle couvre aussi la philologie et les études des langues spécifiques, avec des sections pour les langues les plus largement étudiées comme l'anglais, le français, l'espagnol, et bien d'autres.");
INSERT INTO `dewey`(`code`,`titre`, `description`) VALUES ('500' ,'Sciences',"Cette section regroupe les sciences de la nature, telles que les mathématiques, l'astronomie, la physique, la chimie, les sciences de la terre, et la biologie. Elle inclut les sciences fondamentales et les découvertes concernant l'univers et les lois de la nature.");
INSERT INTO `dewey`(`code`,`titre`, `description`) VALUES ('600' ,'Technologies',"Les ouvrages de cette catégorie abordent les technologies et les sciences appliquées, incluant la médecine, l'ingénierie, l'agriculture, les sciences de la santé, la gestion industrielle, et la cuisine. Elle concerne tout ce qui implique l'application des sciences pour des usages pratiques.");
INSERT INTO `dewey`(`code`,`titre`, `description`) VALUES ('700' ,'Arts et loisirs',"Cette classe inclut l'art sous toutes ses formes : arts visuels, musique, cinéma, théâtre, photographie, ainsi que les activités de loisir. Elle couvre les œuvres artistiques, les techniques d'art et les divers passe-temps tels que le sport et les jeux.");
INSERT INTO `dewey`(`code`,`titre`, `description`) VALUES ('800' ,'Littérature',"Cette catégorie est consacrée aux œuvres littéraires, y compris la poésie, le théâtre, les romans, et la critique littéraire. Elle comprend les littératures de toutes les langues et cultures, et aborde les techniques d'écriture et d'analyse littéraire.");
INSERT INTO `dewey`(`code`,`titre`, `description`) VALUES ('900' ,'Histoire-Geographie',"Cette classe regroupe les ouvrages sur l'histoire, la géographie, les biographies, et les voyages. Elle couvre l'histoire universelle, les histoires nationales, et les descriptions des lieux à travers le monde, de même que les études sur la culture et la civilisation des peuples.");