import { ROLES, STAFF_ROLES } from './accessControl';

const API_URL = 'http://localhost:3000/api';

const roleOptions = [
  { value: ROLES.ADMIN, label: 'Administrator' },
  { value: ROLES.USER, label: 'User' },
  { value: ROLES.INVITER, label: 'Inviter' },
];

export const entityRecords = {
  personne: {
    title: 'Personne',
    listPath: '/Adherent/Personne',
    recordPath: '/Adherent/Personne',
    listEndpoint: `${API_URL}/crud/personnes`,
    updateEndpoint: `${API_URL}/crud/personnes`,
    multipart: true,
    deleteEndpoint: (id) => `${API_URL}/crud/personnes/${id}`,
    idField: 'id',
    editRoles: STAFF_ROLES,
    breadcrumbs: ['Adherent', 'Personne'],
    fields: [
      { name: 'code', label: 'Matricule' },
      { name: 'nom', label: 'Nom' },
      { name: 'prenom', label: 'Prénom' },
      { name: 'CIN', label: 'CIN' },
      { name: 'adresse', label: 'Adresse', type: 'textarea' },
      { name: 'profession', label: 'Profession' },
      { name: 'departement', label: 'Département' },
      { name: 'tel', label: 'Téléphone' },
      { name: 'date_inscription', label: 'Date d’inscription', type: 'date' },
      { name: 'date_nais', label: 'Date de naissance', type: 'date' },
      { name: 'lieu', label: 'Lieu de naissance' },
      { name: 'photo', label: 'Photo', type: 'photo', upload: true, required: false },
    ],
  },
  adherent: {
    title: 'Adhérent',
    listPath: '/Adherent/Adherent',
    recordPath: '/Adherent/Adherent',
    listEndpoint: `${API_URL}/crud/adherents`,
    updateEndpoint: `${API_URL}/crud/adherents`,
    deleteEndpoint: (id) => `${API_URL}/crud/adherents/${id}`,
    idField: 'id_adh',
    editRoles: STAFF_ROLES,
    breadcrumbs: ['Adherent', 'Adherent'],
    fields: [
      { name: 'id_adh', label: 'Identifiant', editable: false },
      { name: 'code', label: 'Matricule', editable: false },
      { name: 'nom', label: 'Nom', editable: false },
      { name: 'prenom', label: 'Prénom', editable: false },
      {
        name: 'categorie',
        label: 'Catégorie',
        type: 'select',
        options: ['Enfant', 'Jeune', 'Adulte'].map((value) => ({ value, label: value })),
      },
      { name: 'date_reinscription', label: 'Date de réadhésion', type: 'date' },
      { name: 'date_fin', label: 'Fin de réadhésion', type: 'date' },
      { name: 'type', label: 'Type', editable: false },
      {
        name: 'id_pers',
        label: 'Personne',
        type: 'remoteSelect',
        sourceEndpoint: `${API_URL}/crud/personnes`,
        sourceValue: 'id',
        sourceLabel: (personne) => `${personne.code} | ${personne.nom} ${personne.prenom || ''}`.trim(),
        excludeAttachedPerson: true,
      },
      { name: 'penaliser', label: 'Niveau de pénalisation', type: 'number' },
      { name: 'sanctionner', label: 'Sanctionné', type: 'boolean' },
      { name: 'nbrLivreEmp', label: 'Nombre de livres empruntés', type: 'number', editable: false },
    ],
  },
  livre: {
    title: 'Livre',
    listPath: '/GestionBibliotheque/EtatDesLivres',
    recordPath: '/GestionBibliotheque/EtatDesLivres',
    listEndpoint: `${API_URL}/crud/livres`,
    updateEndpoint: `${API_URL}/crud/livres`,
    deleteEndpoint: `${API_URL}/crud/livres`,
    deleteWithBody: true,
    idField: 'id_livre',
    editRoles: STAFF_ROLES,
    breadcrumbs: ['Gestion Bibliothèque', 'État des livres'],
    fields: [
      { name: 'id_livre', label: 'Identifiant', editable: false },
      {
        name: 'Type',
        label: 'Type',
        type: 'select',
        options: ['Livre', 'Usuelle', 'Périodique'].map((value) => ({ value, label: value })),
      },
      { name: 'titre', label: 'Titre' },
      { name: 'sous_titre', label: 'Sous-titre', required: false },
      { name: 'auteur', label: 'Auteur' },
      { name: 'editeur', label: 'Éditeur' },
      { name: 'deway', label: 'Dewey' },
      { name: 'cote', label: 'Cote' },
      { name: 'ISBN', label: 'ISBN' },
      { name: 'langue_pays', label: 'Langue / Pays' },
      { name: 'dimension', label: 'Dimension' },
      { name: 'nbre_page', label: 'Nombre de pages', type: 'number' },
      { name: 'etat', label: 'État' },
      { name: 'status', label: 'Statut' },
      { name: 'date_status', label: 'Date du statut', type: 'date' },
      { name: 'photo', label: 'Photo', type: 'photo', required: false },
      { name: 'anneeEdition', label: 'Année d’édition', required: false },
      { name: 'disponible', label: 'Disponible', type: 'boolean' },
      { name: 'idOeuvre', label: 'Identifiant œuvre', type: 'number', required: false, editable: false },
    ],
  },
  emprunt: {
    title: 'Emprunt',
    listPath: '/GestionBibliotheque/EmpruntLivre/nonRendu',
    recordPath: '/GestionBibliotheque/EmpruntLivre/nonRendu',
    listEndpoint: `${API_URL}/crud/livre_emprunts_non_rendu`,
    updateEndpoint: `${API_URL}/crud/livre_emprunts`,
    deleteEndpoint: (id) => `${API_URL}/crud/livre_emprunts/${id}`,
    idField: 'id',
    editRoles: STAFF_ROLES,
    breadcrumbs: ['Gestion Bibliothèque', 'Emprunt livre', 'Non rendu'],
    fields: [
      { name: 'id', label: 'Identifiant', editable: false },
      { name: 'trix', label: 'Adhérent', editable: false },
      { name: 'livrcode', label: 'Livre', editable: false },
      {
        name: 'id_adh',
        label: 'Adhérent',
        type: 'remoteSelect',
        sourceEndpoint: `${API_URL}/crud/adherents`,
        sourceValue: 'id_adh',
        sourceLabel: (adherent) => `${adherent.code} | ${adherent.nom} ${adherent.prenom || ''}`.trim(),
      },
      {
        name: 'id_livre',
        label: 'Livre',
        type: 'remoteSelect',
        sourceEndpoint: `${API_URL}/crud/livres`,
        sourceValue: 'id_livre',
        sourceLabel: (livre) => `${livre.id_livre} | ${livre.titre}`,
      },
      { name: 'date_emprunt', label: 'Date d’emprunt', type: 'date' },
      { name: 'date_retour', label: 'Date de retour', type: 'date' },
      { name: 'renouvelable', label: 'Renouvelable', type: 'boolean' },
    ],
    preparePayload: (record, values) => ({
      ...record,
      ...values,
      code_pers: values.id_adh,
      status: record.status ?? 0,
      dateReelRetour: record.dateReelRetour || '0000-00-00',
    }),
  },
  user: {
    title: 'Utilisateur',
    listPath: '/Parametre/Administrateur/User',
    recordPath: '/Parametre/Administrateur/User',
    listEndpoint: `${API_URL}/crud/users`,
    updateEndpoint: `${API_URL}/crud/users`,
    multipart: true,
    deleteEndpoint: (id) => `${API_URL}/crud/users/${id}`,
    idField: 'id',
    editRoles: [ROLES.ADMIN],
    breadcrumbs: ['Paramètre', 'Administrateur', 'Gestion utilisateur'],
    fields: [
      { name: 'id', label: 'Identifiant', editable: false },
      { name: 'nom', label: 'Nom' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'photo', label: 'Photo', type: 'photo', upload: true, required: false },
      { name: 'roles', label: 'Rôle', type: 'select', options: roleOptions },
      {
        name: 'account_status',
        label: 'Statut du compte',
        type: 'select',
        options: [
          { value: 'active', label: 'Active' },
          { value: 'pending', label: 'Pending' },
          { value: 'blocked', label: 'Blocked' },
        ],
      },
      {
        name: 'user_role_id',
        label: 'User Role Id',
        type: 'select',
        options: [
          { value: 1, label: 'Administrator' },
          { value: 2, label: 'User' },
        ],
      },
    ],
  },
};
